# Generated by Django 3.2.9 on 2021-12-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='comment',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
